### PR TITLE
Simplify dependencies

### PR DESCRIPTION
**Pull request by kulp**
- `libc` is a dev-dependency at best
- `num-traits` is vestigial and unneeded

### CODE REVIEW

**Comment by kulp** [comment]
@Petelliott, I am separately working on removing the implicit dependency on `wget` (in `build-lightning.sh`) because I found I have a system that does not have `wget`, and while using `curl` might be a stop-gap, I think it would be better to use pure-Rust solutions from `build.rs`. Doing so will smooth the way for Windows builds in the future, too.

If you agree with the idea of such changes, would you prefer to see them in the current pull request, or in a separate one ?

**Comment by Petelliott** [comment]
> If you agree with the idea of such changes, would you prefer to see them in the current pull request, or in a separate one ?

i'm okay with them in the current PR

**Comment by kulp** [comment]
> i'm okay with them in the current PR

Great. I might have them ready today, but I might now. It seems silly to bring in `reqwest` and its huge dependency list just to download a tarball, so I am looking for a low-dependency downloader first.

**Comment by kulp** [comment]
The crate builds on a Linux machine I have that does not have `wget`, and it no longer hides any failures occurring within `build-lightning.sh`, so I hope it is a worthwhile set of improvements.

**Pull request merged**
